name: flutter_ble_ota
description: A Flutter app for OTA updates via BLE
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.5
  file_selector: ^1.0.3
  path_provider: ^2.0.15
  permission_handler: ^11.3.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true 